version: '3'
services:
  app:
    restart: always
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    command: sh launch.sh
    depends_on:
      - db
  db:
    restart: always
    image: mysql:8.0.25
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: app_development
      MYSQL_USER: appuser
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_HOST: "%"
    tty: true
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --default-authentication-plugin=mysql_native_password    
    ports:
      - 3306:3306
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
volumes:
  public-data:
  tmp-data:
  log-data: